local_backend: true

backend:
  name: github
  repo: John-Nik/portfolio
  branch: master
  base_url: https://john-nik.com
  auth_endpoint: /api/auth

publish_mode: editorial_workflow

logo_url: https://john-nik.com/admin/icon.svg

media_folder: images

public_folder: images

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/app/content"
    create: true
    slug: "{{link}}"
    fields:
      - {label: "Short Name", name: "title", widget: "string", required: true}
      - {label: "Post's Link", name: "link", widget: "string", required: true}
      - {label: "Full Name", name: "name", widget: "string", required: true}
      - {label: "Picture", name: "img", widget: "image", required: true}
      - {label: "Background Color", name: "backgroundColor", widget: "string", required: true}
      - {label: "Site Link", name: "siteLink", widget: "string", required: false, default: 'no-link'}
      - {label: "Github Repo", name: "githubLink", widget: "string", required: false, default: 'no-link'}
      - {label: "Enabled", name: "isEnabled", widget: "boolean", default: true}
      - {label: "Responsibilities", name: "body", widget: "markdown", required: false}