local_backend: true

backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: images

public_folder: images

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/app/content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Short Name", name: "title", widget: "string"}
      - {label: "Full Name", name: "name", widget: "string"}
      - {label: "Picture", name: "img", widget: "image"}
      - {label: "Site Link", name: "siteLink", widget: "string"}
      - {label: "Github Repo", name: "githubLink", widget: "string"}
      - {label: "Responsibilities", name: "body", widget: "markdown"}