local_backend: true

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: images

public_folder: public

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/app/content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Project Name", name: "title", widget: "string"}
      - {label: "Picture", name: "img", widget: "image"}
      - {label: "Site Link", name: "siteLink", widget: "string"}
      - {label: "Github Repo", name: "githubLink", widget: "string"}
      - {label: "Responsibilities", name: "body", widget: "markdown"}